<?php

declare(strict_types=1);

namespace App\Service;

use App\Model\Entity\User;
use App\Model\Repository\UserRepository;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use League\OAuth2\Client\Provider\Github;
use League\OAuth2\Client\Token\AccessToken;
use Nette\SmartObject;

class AuthService
{
    use SmartObject;

    private Github $provider;


    public function __construct(
        string $clientId,
        string $clientSecret,
        string $redirectUri,
        private UserRepository $userRepository
    ) {
        $this->provider = new Github([
            'clientId'  => $clientId,
            'clientSecret'  => $clientSecret,
            'redirectUri'   => $redirectUri,
        ]);
    }

    public function getAuthorizationUrl(): string
    {
        return $this->provider->getAuthorizationUrl([
            'scope' => ['read:user', 'user:email'],
        ]);
    }

    /**
     * State generated by the OAuth2 provider. Must be stored in the session
     * and strictly verified in the callback to prevent login CSRF.
     */
    public function getState(): string
    {
        return (string) $this->provider->getState();
    }

    public function getAccessToken(string $code): AccessToken
    {
        return $this->provider->getAccessToken('authorization_code', [
            'code' => $code,
        ]);
    }

    public function getUser(AccessToken $token): array
    {
        try {
            $resourceOwner = $this->provider->getResourceOwner($token);
            return $resourceOwner->toArray();
        } catch (IdentityProviderException $e) {
            throw new \RuntimeException('GitHub authentication failed: ' . $e->getMessage(), 0, $e);
        }
    }


    public function findOrCreateUser(array $userData, AccessToken $token): void
    {
        $user = $this->userRepository->findByGithubId($userData['id']);

        if (!$user) {
            $user = new User();
            // GitHub user IDs are integers; the entity property is string-typed
            // and this file uses strict types, so the cast is mandatory.
            $user->githubId = (string) $userData['id'];
            $user->username = $userData['login'];
            $user->name = $userData['name'] ?? $userData['login'];
            // GitHub returns email: null when the user keeps it private.
            $user->email = $userData['email'] ?? $this->fetchPrimaryEmail($token);
            // profileUrl/avatarUrl are rendered as link href / img src.
            // Only accept absolute https URLs; otherwise fall back to
            // deterministic GitHub URLs so the NOT NULL columns stay valid.
            $user->avatarUrl = self::sanitizeUrl(
                $userData['avatar_url'] ?? null,
                'https://avatars.githubusercontent.com/u/' . $user->githubId . '?v=4'
            );
            $user->bio = $userData['bio'];
            $user->profileUrl = self::sanitizeUrl(
                $userData['html_url'] ?? null,
                'https://github.com/' . $userData['login']
            );
            $user->location = $userData['location'];

            $this->userRepository->update($user);
        }
    }

    private static function sanitizeUrl(mixed $url, string $fallback): string
    {
        return is_string($url) && str_starts_with($url, 'https://') ? $url : $fallback;
    }

    /**
     * GitHub's /user endpoint returns email: null for users with a private email,
     * even with the user:email scope. The dedicated /user/emails endpoint lists them.
     */
    private function fetchPrimaryEmail(AccessToken $token): ?string
    {
        try {
            $request = $this->provider->getAuthenticatedRequest(
                'GET',
                'https://api.github.com/user/emails',
                $token
            );
            $emails = $this->provider->getParsedResponse($request);
            if (!is_array($emails)) {
                return null;
            }
            foreach ($emails as $entry) {
                if (is_array($entry) && !empty($entry['primary']) && !empty($entry['verified']) && !empty($entry['email'])) {
                    return (string) $entry['email'];
                }
            }
            foreach ($emails as $entry) {
                if (is_array($entry) && !empty($entry['email'])) {
                    return (string) $entry['email'];
                }
            }
        } catch (\Throwable) {
            // Email is optional; user creation must not fail because of it.
        }

        return null;
    }
}
