services:
  www:
    privileged: true
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/var
      - ./docker/log:/var/logs
      - ./docker/ssl:/etc/apache2/ssl
    networks:
      - net
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      TZ: "${TZ:-Europe/Prague}"
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitalgarden
    volumes:
      - ./docker/data:/var/lib/mysql
    networks:
      - net
    command: mysqld --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    ports:
      - 8080:80
    networks:
      - net
networks:
  net:
    driver: bridge